name: Deploy Flutter App

on:
  push:
    branches: [ main ]
    paths: [ 'speech_to_email_app/**' ]
  pull_request:
    branches: [ main ]
    paths: [ 'speech_to_email_app/**' ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./speech_to_email_app
      
      - name: Run tests
        run: flutter test
        working-directory: ./speech_to_email_app
      
      - name: Build web
        run: flutter build web
        working-directory: ./speech_to_email_app

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.0'
          channel: 'stable'
      
      - name: Install dependencies
        run: flutter pub get
        working-directory: ./speech_to_email_app
      
      - name: Build web
        run: flutter build web
        working-directory: ./speech_to_email_app
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      
      - name: Deploy to S3
        run: |
          aws s3 sync ./speech_to_email_app/build/web s3://${{ secrets.S3_BUCKET_NAME }} --delete
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/*"